# slsync config file
# Edit these paths to match your system

DOWNLOAD_FOLDERS:
  - /Users/sinanjasar/Downloads
  - /Users/sinanjasar/Music/Soulseek/Downloads/complete
  # Add more folders as needed
DEST_FOLDER: "/Users/sinanjasar/Music/crazyniga2141/Media.localized/Automatically Add to Music.localized"

SUPPORTED_EXTENSIONS:
  - .mp3
  - .flac
  - .wav
  - .aac
  - .m4a
  - .ogg
  - .alac
