# slsync config file
# Edit these paths to match your system

DOWNLOAD_FOLDERS:
  - 'path/to/your/downloads/folder'
  # Add more folders as needed
DEST_FOLDER: "path/to/Automatically Add to Music.localized"

LIBRARY_FOLDER: "path/to/your/library/folder"

SUPPORTED_EXTENSIONS:
  - .mp3
  - .flac
  - .wav
  - .aac
  - .m4a
  - .ogg
  - .alac

# Duplicate skipping configuration
SKIP_DUPLICATES:
  ENABLED: NO  # YES or NO
  CRITERIA:
    METADATA:
      TITLE: NO
      ARTIST: NO
      ALBUM: NO
      TRACKNUMBER: NO
      YEAR: NO
      GENRE: NO
    AUDIO_PROPERTIES:
      DURATION: YES
      BITRATE: YES
      SAMPLE_RATE: YES
      CHANNELS: NO
      CODEC: NO
    AUDIO_HASH: NO  # YES or NO